command: ["streamlit", "run", "app.py"]
env:
  - name: STREAMLIT_SERVER_ADDRESS
    value: "0.0.0.0"
  - name: STREAMLIT_SERVER_PORT
    valueFrom: DATABRICKS_APP_PORT
  - name: STREAMLIT_SERVER_HEADLESS
    value: "true"
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
